/**
 * @fileoverview Regression tests for P0-3: credentials generated by the auth
 * service must come from a CSPRNG, never Math.random().
 *
 * @author NooblyJS Team
 * @since 1.1.0
 */

'use strict';

const fs = require('node:fs');
const path = require('node:path');
const EventEmitter = require('events');
const createAuthService = require('../../../src/authservice');

describe('Auth service secure randomness (P0-3)', () => {
  let auth;

  beforeEach(() => {
    auth = createAuthService('memory', {}, new EventEmitter());
  });

  it('generateStrongPassword returns 16 chars with every character class', () => {
    const password = auth.generateStrongPassword();
    expect(password).toHaveLength(16);
    expect(password).toMatch(/[A-Z]/);
    expect(password).toMatch(/[a-z]/);
    expect(password).toMatch(/[0-9]/);
    expect(password).toMatch(/[^A-Za-z0-9]/);
  });

  it('generateStrongPassword does not use Math.random', () => {
    const spy = jest.spyOn(Math, 'random');
    auth.generateStrongPassword();
    expect(spy).not.toHaveBeenCalled();
    spy.mockRestore();
  });

  it('generateStrongPassword produces distinct values', () => {
    const passwords = new Set(Array.from({ length: 200 }, () => auth.generateStrongPassword()));
    expect(passwords.size).toBe(200);
  });

  it('no server-side authservice source uses Math.random', () => {
    const root = path.join(__dirname, '../../../src/authservice');
    const offenders = [];
    const walk = (dir) => {
      for (const entry of fs.readdirSync(dir, { withFileTypes: true })) {
        const full = path.join(dir, entry.name);
        if (entry.isDirectory()) walk(full);
        else if (entry.name.endsWith('.js') && fs.readFileSync(full, 'utf8').includes('Math.random')) {
          offenders.push(path.relative(root, full));
        }
      }
    };
    walk(root);
    expect(offenders).toEqual([]);
  });
});
