### Working API Status
GET http://localhost:3000/api/working/status

### Working API Run
POST http://localhost:3000/api/working/run
Content-Type: application/json

{
  "task": "../../../tests/working/exampleTask.js",
  "data": {
    "input": "someData"
  }
}
